project:
  type: website
  output-dir: docs

website:
  title: "Faustine Fan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      
      


format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    href: Resume.pdf
    text: CV
    


editor: visual



